### ISSUE TITLE
Privileges

### ISSUE THREAD

**Issue by husseinalhammad** [Pipits/pipit-catalog#1]
Originally posted on Perch Forum [here](http://forum.grabaperch.com/forum/04-24-2018-pipits-catalog-permissions-not-showing-up-in-perms-list).

> I am running the latest Perch Runway version and Pipits Catalog. The app works fine, but for some reason the permissions are not showing up in the list for me to add the access to other users besides admin.

**Comment by kevinwolff** [comment]
I checked the permissions template file and it seems pipits catalog is visible there. I also went to the menu system in Perch Runway and under the Catalog node added access for any user who also has permission to create products in shop. Unfortunately it didn't work.

**Comment by husseinalhammad** [comment]
@kevinwolff I've added the missing privilege to [v1.2.1](https://github.com/Pipits/pipit-catalog/releases/tag/v1.2.1). 

To update the app:

* replace the `pipit_catalog` folder with the new one
* log in as admin and go to the Catalog app - you should get an update message


After the update you should be able to add the privilege to access the Catalog app to any role.
